export default (() => {
  return {
    welcomeLogo: require('../assets/images/home.png'),
    leftArrow: require('../assets/images/left-arrow.png'),
    rightArrow: require('../assets/images/right-arrow.png'),
    check: require('../assets/images/checkbox.png'),
    uncheck: require('../assets/images/blank-check-box.png'),
    backSpace: require('../assets/images/back-space.png'),
    splash: require('../assets/images/splash.png'),
    profile: require('../assets/images/profile.png'),
    provinces: require('../assets/images/area.png'),
    provincesSelected: require('../assets/images/area-selected.png'),
    favorite: require('../assets/images/heart.png'),
    favoriteSelected: require('../assets/images/heart-selected.png'),
    more: require('../assets/images/open-menu.png'),
    moreSelected: require('../assets/images/open-menu-selected.png'),
    main: require('../assets/images/main.png'),
    mainSelected: require('../assets/images/mainSelected.png'),
    photo: require('../assets/images/photo.png'),
    location: require('../assets/images/location.png'),
    bathroom: require('../assets/images/bathroom.png'),
    bed: require('../assets/images/bed.png'),
    expand: require('../assets/images/expand.png'),
    tub: require('../assets/images/tub.png'),
    bell: require('../assets/images/bell.png'),
    searchIcon: require('../assets/images/search.png'),
    list: require('../assets/images/list.png'),
    filter: require('../assets/images/filter.png'),
    downArrow: require('../assets/images/down-arrow.png'),
    downArrowDark: require('../assets/images/down-arrow-dark.png'),
    cover: require('../assets/images/cover.png'),
    map: require('../assets/images/map.png'),
    plus: require('../assets/images/plus.png'),
    logout: require('../assets/images/logout.png'),
    user: require('../assets/images/user.png'),
    share: require('../assets/images/share.png'),
    arrowDetail: require('../assets/images/arrow-detail.png'),
    pin: require('../assets/images/pinView.png'),
    pinSelected: require('../assets/images/pinselected.png'),
    slide1: require('../assets/images/slide1.png'),
    slide2: require('../assets/images/slide2.png'),
    slide3: require('../assets/images/slide3.png'),
    heartRed: require('../assets/images/heart-red.png'),
    spam: require('../assets/images/spam.png'),
    bedSelected: require('../assets/images/bed_selected.png'),
    starSelected: require('../assets/images/star-selected.png'),
    star: require('../assets/images/star.png'),
    bathRoomSelected: require('../assets/images/bathroom-selected.png'),
    tubSelected: require('../assets/images/tub-selected.png'),
    call: require('../assets/images/call.png'),
    locationBlack: require('../assets/images/location-black.png'),
    rightArrowWhite: require('../assets/images/right-arrow-white.png'),
    closeIcon: require('../assets/images/close.png'),
    menuIcon: require('../assets/images/menu.png'),
    starGray: require('../assets/images/gray-star.png'),
    starWhite: require('../assets/images/white-star.png'),
    plusIcon: require('../assets/images/plus-grey.png'),
    minusIcon: require('../assets/images/minus.png'),
    callBlack: require('../assets/images/call-black.png'),
    export: require('../assets/images/export.png'),
    warning: require('../assets/images/warning.png'),
    heartGray: require('../assets/images/heart-gray.png'),
    sort: require('../assets/images/sort.png'),
    myProperty: require('../assets/images/myProperty.png'),
    payingoff: require('../assets/images/payingoff.png'),
    setting: require('../assets/images/setting.png'),
    rateApp: require('../assets/images/more_star.png'),
    help: require('../assets/images/help.png'),
    roundCheck: require('../assets/images/round_check.png'),
    roundUnCheck: require('../assets/images/round_uncheck.png'),
    checkSelected: require('../assets/images/checkSelected.png'),
    filterUncheck: require('../assets/images/filter_uncheck.png'),
    filterCheck: require('../assets/images/filter_check.png'),
    camera: require('../assets/images/camera.png'),
    closeBig:require('../assets/images/close_add.png'),
    moreAction:require('../assets/images/more-action.png'),
    repeat:require('../assets/images/repeat.png'),
    delete:require('../assets/images/delete.png'),
    checksel:require('../assets/images/check-select.png'),
    unchecksel:require('../assets/images/check-unselect.png'),
    phone:require('../assets/images/phone.png'),
    leftArrowWhite:require('../assets/images/left-white.png'),
    type:require('../assets/images/type.png'),
    typeBlack:require('../assets/images/land_type.png'),
    road:require('../assets/images/road.png'),
    roadBlue:require('../assets/images/road-blue.png'),
    door:require('../assets/images/open-door.png'),
    doorBlue:require('../assets/images/open-door-blue.png'),
    country_logo:require('../assets/images/country_logo.png'),
    map_home:require('../assets/images/map-home.png'),
    contact_us:require('../assets/images/contactUs.png'),
    contactByEmail:require('../assets/images/contactByEmail.png'),
    contactByPhone:require('../assets/images/contactByPhone.png'),
    shareIcon:require('../assets/images/share_icon.png'),
    appartmentSale:require('../assets/images/appartment_sale.jpeg'),
    appartmentRent:require('../assets/images/appartment_rent.jpeg'),
    buildingSale:require('../assets/images/building_sale.jpeg'),
    buildingRent:require('../assets/images/building_rent.jpeg'),
    homeSale:require('../assets/images/home_sale.jpeg'),
    homeRent:require('../assets/images/home_rent.jpeg'),
    landSale:require('../assets/images/land_sale.jpeg'),
    landRent:require('../assets/images/land_rent.jpeg'),
    officeSale:require('../assets/images/office_sale.jpeg'),
    officeRent:require('../assets/images/office_rent.jpeg'),
    shopSale:require('../assets/images/shop_sale.jpeg'),
    shopRent:require('../assets/images/shop_rent.jpeg'),
    villaSale:require('../assets/images/villa_sale.jpeg'),
    wareHouseSale:require('../assets/images/warehouse_sale.jpeg'),
    wareHouseRent:require('../assets/images/warehouse_rent.jpeg'),
    editProfile: require("../assets/images/pencil.png")


  };
})();
